import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import CarLanding from "../public/images/carLanding.png";
import Image from "next/image";
import "bootstrap/dist/css/bootstrap.css";
import { Container, Row, Col } from "reactstrap";
import SearchCarForm from "../components/searchCarForm";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Book a vehicle App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div>
          <h1>
            RENT&GO <br />
            <br />
            Easy cars’ rent with us. Let’s start!
          </h1>
        </div>
        <div className={styles.backImg}>
          <Image
            src={CarLanding}
            alt="Picture of the car"
            height={400}
            responsive
          />
        </div>
        <div>
          <Container>
            <Row>
              <Col lg="4" md="10" sm="12">
                <div>
                  <h2 className={styles.search_form_title}>
                    Find the best car for you now
                  </h2>
                </div>
              </Col>
              <Col lg="8" md="10" sm="12">
                <SearchCarForm />
              </Col>
            </Row>
          </Container>
        </div>
      </main>
    </>
  );
}
