import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import {carLanding} from "../public/images/carLanding.jpg";
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Book a vehicle App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div>Hello</div> 
      <Image
          src="/public/images/carLanding.jpg"
          alt="Picture of the car"
          width={500}
          height={500}
          object-fit="contain" 
          /> 
          <div>Card with options</div>
      </main>
    </>
  )
}
